#* mise (node/python/... version manager, replaced nvm) — activate hooks PATH per directory from
#* .config/mise/config.toml + per-project mise.toml/.node-version. Completions come from
#* ~/.zsh/completions/_mise, generated by initSystem/initApt.sh.
eval "$(mise activate zsh --shims)" # should be first
eval "$(mise activate zsh)"
